export interface JobRole {
  slug: string
  title: string
  iconName: string
  department: string        // 'Engineering' | 'AI & Machine Learning' | 'Operations' | 'Marketing' | 'Sales'
  type: string              // 'Graduate Trainee' | 'Internship' | 'Full-time' (for future roles)
  duration: string          // '3 months', '2 months', 'Full-time'
  startDate: string
  deadline: string
  location: string
  summary: string
  about: string
  responsibilities: string[]
  requirements: string[]
  niceToHave: string[]
  whatYouWillLearn: string[]
}

export const allJobs: JobRole[] = [
  {
    slug: 'backend-developer',
    title: 'Backend (Django) Developer',
    iconName: 'Server',
    department: 'Engineering',
    type: 'Graduate Trainee',
    duration: '3 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Build and maintain the APIs and backend systems that power Mediloop healthcare platform.',
    about: 'As a Backend Developer Trainee, you will work directly with our engineering team to build and maintain the REST APIs, database models, and backend logic that power Mediloop. You will work with Django and Django REST Framework to build production-grade healthcare software used by hospitals, clinics, and pharmacies across Uganda. This is a hands-on role where you will ship real code from week one.',
    responsibilities: [
      'Build and maintain REST APIs using Django and Django REST Framework',
      'Design and manage PostgreSQL database schemas and write migrations',
      'Implement authentication, authorization, and security features',
      'Write unit tests and integration tests for all new features',
      'Collaborate with frontend, AI, and DevOps teams on feature delivery',
      'Participate in code reviews and contribute to technical documentation',
      'Debug and resolve production issues as part of the on-call rotation',
      'Work with task queues for background processing of healthcare data',
    ],
    requirements: [
      'Proficiency in Python programming',
      'Understanding of REST API design principles',
      'Basic knowledge of Git version control',
      'Familiarity with SQL and relational databases',
      'Strong problem-solving skills and attention to detail',
    ],
    niceToHave: [
      'Experience with Django or Django REST Framework',
      'Familiarity with Docker and containerization',
      'Knowledge of Redis, Celery, or task queue systems',
      'Understanding of healthcare data standards (FHIR, HL7)',
    ],
    whatYouWillLearn: [
      'Production-grade Django and DRF development',
      'Healthcare software architecture and data modeling',
      'API security, authentication, and authorization patterns',
      'CI/CD pipelines and deployment workflows',
      'FHIR healthcare data standards',
    ],
  },
  {
    slug: 'frontend-developer',
    title: 'Frontend (React/Next.js) Developer',
    iconName: 'Code',
    department: 'Engineering',
    type: 'Graduate Trainee',
    duration: '3 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Build the user interfaces that healthcare providers and patients interact with every day.',
    about: 'As a Frontend Developer Trainee, you will build responsive, accessible user interfaces for Mediloop provider portal, admin dashboard, and patient-facing applications. You will work with React, Next.js, TypeScript, and Tailwind CSS to create production-quality healthcare software.',
    responsibilities: [
      'Build responsive user interfaces with React and Next.js',
      'Implement UI components using Tailwind CSS and shadcn/ui component library',
      'Integrate with backend REST APIs and manage application state',
      'Ensure cross-browser compatibility and mobile responsiveness',
      'Write clean, maintainable TypeScript code with proper typing',
      'Write component tests and end-to-end tests',
      'Optimize application performance and loading times',
    ],
    requirements: [
      'Proficiency in JavaScript and TypeScript',
      'Solid understanding of React fundamentals (hooks, state, props)',
      'Knowledge of CSS, Tailwind CSS, or similar utility-first frameworks',
      'Basic knowledge of Git version control',
      'Eye for detail and good sense of UI/UX',
    ],
    niceToHave: [
      'Experience with Next.js (App Router)',
      'Familiarity with testing libraries (Vitest, Playwright)',
      'Knowledge of state management (Zustand, React Query)',
      'Understanding of accessibility standards (WCAG)',
    ],
    whatYouWillLearn: [
      'Production React and Next.js development patterns',
      'Building complex healthcare UIs with real-time data',
      'TypeScript best practices in large codebases',
      'Component architecture and design system development',
      'Performance optimization for low-bandwidth environments',
    ],
  },
  {
    slug: 'ai-ml-developer',
    title: 'AI/ML Developer',
    iconName: 'Brain',
    department: 'AI & Machine Learning',
    type: 'Graduate Trainee',
    duration: '3 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Develop AI models that assist healthcare providers with clinical decision-making.',
    about: 'As an AI/ML Developer Trainee, you will work on the AI systems that power Mediloop clinical decision support, natural language processing, and intelligent healthcare features. You will develop and fine-tune machine learning models for medical use cases, build NLP pipelines for clinical text, and integrate AI capabilities into production APIs.',
    responsibilities: [
      'Develop and fine-tune machine learning models for clinical use cases',
      'Build natural language processing pipelines for medical text analysis',
      'Work with vector databases and retrieval-augmented generation (RAG)',
      'Integrate AI models into production REST APIs',
      'Evaluate model performance with healthcare-specific metrics',
      'Process and prepare medical datasets for training and evaluation',
      'Collaborate with clinical advisors to validate AI outputs',
    ],
    requirements: [
      'Proficiency in Python programming',
      'Understanding of machine learning fundamentals',
      'Experience with PyTorch or TensorFlow',
      'Basic knowledge of natural language processing',
      'Familiarity with data processing libraries (pandas, NumPy)',
    ],
    niceToHave: [
      'Experience with large language models (LLMs) and prompt engineering',
      'Knowledge of healthcare AI applications',
      'Familiarity with vector databases',
      'Experience with RAG architectures',
    ],
    whatYouWillLearn: [
      'Building production AI systems for healthcare',
      'Clinical NLP and medical text processing',
      'RAG architecture and vector search systems',
      'AI model evaluation in safety-critical domains',
      'Responsible AI practices in healthcare',
    ],
  },
  {
    slug: 'devops-cloud-engineer',
    title: 'DevOps/Cloud Engineer',
    iconName: 'Cloud',
    department: 'Engineering',
    type: 'Graduate Trainee',
    duration: '3 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Manage the cloud infrastructure and deployment pipelines that keep Mediloop running 24/7.',
    about: 'As a DevOps/Cloud Engineer Trainee, you will help manage the infrastructure that powers Mediloop healthcare platform. You will work with cloud services, containerization, CI/CD pipelines, and monitoring systems to ensure our platform is reliable, secure, and performant.',
    responsibilities: [
      'Manage cloud infrastructure and deployment pipelines',
      'Set up and maintain CI/CD workflows using GitHub Actions',
      'Monitor system performance, uptime, and resource usage',
      'Containerize applications with Docker and manage orchestration',
      'Implement security best practices and access controls',
      'Automate infrastructure provisioning and configuration',
      'Troubleshoot production incidents and perform root cause analysis',
    ],
    requirements: [
      'Basic Linux system administration skills',
      'Familiarity with Docker and containerization concepts',
      'Understanding of CI/CD concepts and workflows',
      'Experience with at least one cloud platform (AWS, GCP, or Azure)',
      'Basic networking knowledge (DNS, HTTP, SSL/TLS)',
    ],
    niceToHave: [
      'Experience with Kubernetes or container orchestration',
      'Knowledge of Terraform or infrastructure-as-code tools',
      'Familiarity with monitoring tools (Prometheus, Grafana)',
      'Experience with Nginx or reverse proxy configuration',
    ],
    whatYouWillLearn: [
      'Production cloud infrastructure management',
      'CI/CD pipeline design for healthcare applications',
      'Container orchestration and microservices deployment',
      'Infrastructure security and compliance for health data',
      'Monitoring, alerting, and incident response',
    ],
  },
  {
    slug: 'it-intern',
    title: 'IT Intern',
    iconName: 'Monitor',
    department: 'Engineering',
    type: 'Internship',
    duration: '2 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Support the technical team and learn about healthcare technology systems.',
    about: 'As an IT Intern at Mediloop, you will provide technical support to the team and gain hands-on experience with healthcare technology systems. You will assist with system setup, maintenance, documentation, and testing.',
    responsibilities: [
      'Provide technical support to the engineering and operations teams',
      'Assist with system setup, configuration, and maintenance',
      'Help with software testing and quality assurance',
      'Create and maintain technical documentation',
      'Support user onboarding and training for healthcare providers',
      'Assist with hardware and network troubleshooting',
    ],
    requirements: [
      'Currently enrolled in a university IT, Computer Science, or related program',
      'Basic understanding of computer systems and networking',
      'Willingness to learn and take on new challenges',
      'Good communication and organizational skills',
      'University introductory letter required',
    ],
    niceToHave: [
      'Basic programming knowledge',
      'Familiarity with Linux or command line tools',
    ],
    whatYouWillLearn: [
      'Healthcare technology systems and infrastructure',
      'IT support best practices in a startup environment',
      'Software testing and quality assurance processes',
      'Technical documentation and knowledge management',
    ],
  },
  {
    slug: 'marketing-intern',
    title: 'Marketing Intern',
    iconName: 'Megaphone',
    department: 'Marketing',
    type: 'Internship',
    duration: '2 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Help grow Mediloop brand and reach more healthcare providers and patients across Uganda.',
    about: 'As a Marketing Intern at Mediloop, you will help build and execute marketing strategies that grow our reach among healthcare providers and patients across Uganda. You will create content, manage social media, conduct market research, and support campaigns.',
    responsibilities: [
      'Create engaging content for social media platforms (Twitter, LinkedIn, Instagram)',
      'Help plan and execute digital marketing campaigns',
      'Conduct market research on healthcare trends in Uganda',
      'Support brand awareness and community engagement initiatives',
      'Assist with email marketing and newsletter creation',
      'Track and report on marketing metrics and campaign performance',
    ],
    requirements: [
      'Currently enrolled in a university Marketing, Communications, or related program',
      'Strong written and verbal communication skills',
      'Familiarity with social media platforms and digital marketing basics',
      'Creative thinking and attention to detail',
      'University introductory letter required',
    ],
    niceToHave: [
      'Experience with Canva or design tools',
      'Knowledge of SEO basics',
      'Familiarity with email marketing platforms',
    ],
    whatYouWillLearn: [
      'Health-tech marketing strategies and best practices',
      'Content creation and social media management',
      'Market research and competitive analysis',
      'Campaign planning, execution, and measurement',
    ],
  },
  {
    slug: 'sales-intern',
    title: 'Sales Intern',
    iconName: 'TrendingUp',
    department: 'Sales',
    type: 'Internship',
    duration: '2 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Support the sales team in bringing more healthcare facilities onto the Mediloop platform.',
    about: 'As a Sales Intern at Mediloop, you will support the sales team in outreach to healthcare providers, help prepare presentations and proposals, and learn the fundamentals of B2B healthcare sales.',
    responsibilities: [
      'Support the sales team in outreach to healthcare providers',
      'Help prepare sales presentations, proposals, and demos',
      'Assist with CRM data management and pipeline tracking',
      'Conduct research on potential healthcare facility leads',
      'Participate in client meetings and facility visits',
      'Track and report on sales activities and outcomes',
    ],
    requirements: [
      'Currently enrolled in a university Business, Sales, Marketing, or related program',
      'Strong interpersonal and communication skills',
      'Self-motivated with a results-oriented mindset',
      'Comfortable with phone calls and in-person meetings',
      'University introductory letter required',
    ],
    niceToHave: [
      'Prior sales or customer service experience',
      'Familiarity with CRM tools',
      'Knowledge of Uganda healthcare landscape',
    ],
    whatYouWillLearn: [
      'B2B healthcare sales processes and strategies',
      'CRM tools and sales pipeline management',
      'Presentation and proposal development',
      'Client relationship management in healthcare',
    ],
  },
  {
    slug: 'admin-intern',
    title: 'Admin Intern',
    iconName: 'ClipboardList',
    department: 'Operations',
    type: 'Internship',
    duration: '2 months',
    startDate: 'June 2025',
    deadline: 'May 15, 2025',
    location: 'Kampala, Uganda',
    summary: 'Support day-to-day operations and help keep the Mediloop team running smoothly.',
    about: 'As an Admin Intern at Mediloop, you will support the day-to-day operations of a fast-growing health-tech startup. You will assist with scheduling, coordination, document management, and administrative tasks across HR, finance, and operations.',
    responsibilities: [
      'Support day-to-day office operations and logistics',
      'Assist with scheduling, calendar management, and coordination',
      'Help with document management, filing, and record keeping',
      'Support HR with recruitment coordination and onboarding',
      'Assist the finance team with basic administrative tasks',
      'Help organize team events, meetings, and workshops',
    ],
    requirements: [
      'Currently enrolled in a university Business Administration, Management, or related program',
      'Strong organizational and time management skills',
      'Good written and verbal communication',
      'Proficiency in Microsoft Office or Google Workspace',
      'University introductory letter required',
    ],
    niceToHave: [
      'Prior administrative or office experience',
      'Familiarity with project management tools',
    ],
    whatYouWillLearn: [
      'Startup operations and office management',
      'HR processes including recruitment and onboarding',
      'Financial administration basics',
      'Professional communication and stakeholder management',
    ],
  },
]

export function getJobBySlug(slug: string): JobRole | undefined {
  return allJobs.find((job) => job.slug === slug)
}

export const departments = ['All', ...Array.from(new Set(allJobs.map((j) => j.department)))]
export const jobTypes = ['All', ...Array.from(new Set(allJobs.map((j) => j.type)))]
